const CANVAS_W = 1280;
const CANVAS_H = 720;

const TEMPLATES = [
  {
    id: "two-subject",
    name: "Two subjects over a scene",
    description: "A background scene with a cut-out subject on each side and a headline across the top.",
    slots: [
      {
        key: "background",
        label: "Background scene",
        type: "image",
        cutout: false,
        treat: "background",
        z: 0,
        rect: { x: 0, y: 0, w: 1, h: 1 },
      },
      {
        key: "subjectLeft",
        label: "Left subject",
        type: "image",
        cutout: true,
        anchor: "left",
        z: 1,
        rect: { x: 0, y: 0, w: 0.44, h: 1 },
        defaults: { zoom: 0.96 },
      },
      {
        key: "subjectRight",
        label: "Right subject (your host)",
        type: "image",
        cutout: true,
        anchor: "right",
        z: 2,
        rect: { x: 0.56, y: 0, w: 0.44, h: 1 },
        defaults: { zoom: 0.96 },
      },
      {
        key: "headline",
        label: "Headline",
        type: "text",
        style: "headline",
        z: 3,
        rect: { x: 0.26, y: 0.2, w: 0.5, h: 0.44 },
        defaults: { text: "", font: "intertight", color: "#FFFFFF", accentColor: "#FF2A1A", strokeColor: "#000000", depthColor: "#1A0605", rotate: -4, depth: 10, scale: 0.36 },
      },
    ],
  },
  {
    id: "split-screen",
    name: "Split screen, before and after",
    description: "Two panels side by side under a banner headline.",
    slots: [
      {
        key: "banner",
        label: "Banner headline",
        type: "text",
        z: 3,
        rect: { x: 0.02, y: 0.02, w: 0.96, h: 0.22 },
        defaults: { text: "", font: "archivo", color: "#FFFFFF", strokeColor: "#000000", scale: 0.1 },
      },
      {
        key: "before",
        label: "Before",
        type: "image",
        cutout: false,
        z: 0,
        rect: { x: 0, y: 0.26, w: 0.495, h: 0.74 },
      },
      {
        key: "after",
        label: "After",
        type: "image",
        cutout: false,
        z: 0,
        rect: { x: 0.505, y: 0.26, w: 0.495, h: 0.74 },
      },
    ],
  },
  {
    id: "host-right",
    name: "Host on the right, topic on the left",
    description: "A clean background, your headline and a graphic on the left, and you cut out on the right.",
    slots: [
      {
        key: "background",
        label: "Background",
        type: "image",
        cutout: false,
        treat: "background",
        z: 0,
        rect: { x: 0, y: 0, w: 1, h: 1 },
      },
      {
        key: "graphic",
        label: "Logo or screenshot",
        type: "image",
        cutout: false,
        fit: "contain",
        z: 1,
        rect: { x: 0.04, y: 0.46, w: 0.56, h: 0.5 },
      },
      {
        key: "host",
        label: "You",
        type: "image",
        cutout: true,
        anchor: "right",
        z: 2,
        rect: { x: 0.62, y: 0, w: 0.38, h: 1 },
        defaults: { zoom: 0.98 },
      },
      {
        key: "headline",
        label: "Headline",
        type: "text",
        z: 3,
        rect: { x: 0.03, y: 0.03, w: 0.58, h: 0.52 },
        defaults: { text: "", font: "intertight", color: "#111114", strokeColor: "#FFFFFF", scale: 0.13 },
      },
    ],
  },
  {
    id: "side-panel",
    name: "Full bleed with stacked headline",
    description: "One strong image with a headline block stacked over the right side.",
    slots: [
      {
        key: "background",
        label: "Main image",
        type: "image",
        cutout: false,
        z: 0,
        rect: { x: 0, y: 0, w: 1, h: 1 },
      },
      {
        key: "headline",
        label: "Headline",
        type: "text",
        z: 2,
        rect: { x: 0.34, y: 0.58, w: 0.62, h: 0.36 },
        defaults: { text: "", font: "bigshoulders", color: "#FFFFFF", strokeColor: "#000000", scale: 0.14 },
      },
    ],
  },
  {
    id: "photo-headline",
    name: "Your photo with a headline stack",
    description: "One photo of you or your guests, with a bold stacked headline, a label and a quote over a dark fade on the left.",
    slots: [
      {
        key: "photo",
        label: "Your photo",
        type: "image",
        cutout: false,
        fill: "extend",
        anchor: "right",
        z: 0,
        rect: { x: 0, y: 0, w: 1, h: 1 },
      },
      {
        key: "headline",
        label: "Headline",
        type: "text",
        style: "stack",
        scrim: "left",
        z: 3,
        rect: { x: 0.045, y: 0.06, w: 0.5, h: 0.88 },
        defaults: {
          text: "",
          font: "anton",
          color: "#FFFFFF",
          strokeColor: "#000000",
          scale: 0.15,
          align: "left",
          caps: true,
          shadow: true,
          stroke: false,
          gap: 0.05,
          boxRadius: 0.04,
        },
      },
    ],
  },
  {
    id: "host-headline",
    name: "You on the right, bold headline on the left",
    description: "You cut out on the right, with a big headline stack on the left that can circle, box or colour one word.",
    slots: [
      {
        key: "background",
        label: "Background",
        type: "image",
        cutout: false,
        treat: "background",
        z: 0,
        rect: { x: 0, y: 0, w: 1, h: 1 },
      },
      {
        key: "host",
        label: "You",
        type: "image",
        cutout: true,
        anchor: "right",
        z: 2,
        rect: { x: 0.5, y: 0.04, w: 0.5, h: 0.96 },
        defaults: { zoom: 1 },
      },
      {
        key: "headline",
        label: "Headline",
        type: "text",
        style: "stack",
        z: 3,
        rect: { x: 0.04, y: 0.06, w: 0.52, h: 0.88 },
        defaults: {
          text: "",
          font: "anton",
          supportFont: "barlowcondensed",
          color: "#FFFFFF",
          strokeColor: "#000000",
          scale: 0.16,
          align: "left",
          caps: true,
          shadow: true,
          stroke: false,
          gap: 0.02,
          boxRadius: 0.12,
        },
      },
    ],
  },
  {
    id: "photo-bottom",
    name: "Group photo with a big headline along the bottom",
    description: "One wide photo of you or your group, with a big centred headline over a dark fade along the bottom.",
    decor: [{ type: "fade", color: "#050A14", from: 0.42, opacity: 0.97, z: 1 }],
    slots: [
      {
        key: "photo",
        label: "Your photo",
        type: "image",
        cutout: false,
        fill: "extend",
        anchor: "center",
        z: 0,
        rect: { x: 0, y: 0, w: 1, h: 1 },
      },
      {
        key: "headline",
        label: "Headline",
        type: "text",
        style: "stack",
        z: 3,
        rect: { x: 0.04, y: 0.58, w: 0.92, h: 0.4 },
        defaults: {
          text: "",
          font: "poppinsblack",
          supportFont: "barlowcondensed",
          color: "#FFFFFF",
          strokeColor: "#000000",
          scale: 0.15,
          align: "center",
          caps: true,
          shadow: true,
          stroke: false,
          italic: true,
          gap: 0.01,
        },
      },
    ],
  },
  {
    id: "three-panel",
    name: "Three photos with a centred headline",
    description: "Three slanted photo panels side by side, with a big centred headline over a dark fade along the bottom.",
    decor: [
      { type: "line", from: [0.325, 0], to: [0.355, 1], color: "#FFFFFF", width: 6, z: 3 },
      { type: "line", from: [0.675, 0], to: [0.645, 1], color: "#FFFFFF", width: 6, z: 3 },
      { type: "fade", color: "#0A1330", from: 0.3, opacity: 0.98, z: 4 },
    ],
    slots: [
      {
        key: "panelLeft",
        label: "Left photo",
        type: "image",
        cutout: false,
        z: 0,
        rect: { x: 0, y: 0, w: 0.355, h: 1 },
        clip: [[0, 0], [0.325, 0], [0.355, 1], [0, 1]],
      },
      {
        key: "panelCenter",
        label: "Middle photo",
        type: "image",
        cutout: false,
        z: 1,
        rect: { x: 0.325, y: 0, w: 0.35, h: 1 },
        clip: [[0.325, 0], [0.675, 0], [0.645, 1], [0.355, 1]],
      },
      {
        key: "panelRight",
        label: "Right photo",
        type: "image",
        cutout: false,
        z: 2,
        rect: { x: 0.645, y: 0, w: 0.355, h: 1 },
        clip: [[0.675, 0], [1, 0], [1, 1], [0.645, 1]],
      },
      {
        key: "headline",
        label: "Headline",
        type: "text",
        style: "stack",
        z: 5,
        rect: { x: 0.1, y: 0.36, w: 0.8, h: 0.62 },
        defaults: {
          text: "",
          font: "poppinsblack",
          supportFont: "barlowcondensed",
          color: "#FFFFFF",
          strokeColor: "#000000",
          scale: 0.12,
          align: "center",
          caps: true,
          shadow: true,
          stroke: false,
          gap: 0.03,
        },
      },
    ],
  },
];

const byId = (id) => TEMPLATES.find((t) => t.id === id) || null;

const DEFAULT_TEMPLATE = TEMPLATES[0].id;

const imageSlots = (template) => template.slots.filter((s) => s.type === "image");
const textSlots = (template) => template.slots.filter((s) => s.type === "text");

const pixelRect = (rect) => ({
  left: Math.round(rect.x * CANVAS_W),
  top: Math.round(rect.y * CANVAS_H),
  width: Math.max(1, Math.round(rect.w * CANVAS_W)),
  height: Math.max(1, Math.round(rect.h * CANVAS_H)),
});

const summarize = (template) => ({
  id: template.id,
  name: template.name,
  description: template.description,
  slots: template.slots.map((s) => ({
    key: s.key,
    label: s.label,
    type: s.type,
    cutout: Boolean(s.cutout),
    anchor: s.anchor || "center",
    defaults: s.defaults || null,
  })),
});

module.exports = {
  TEMPLATES,
  DEFAULT_TEMPLATE,
  CANVAS_W,
  CANVAS_H,
  byId,
  imageSlots,
  textSlots,
  pixelRect,
  summarize,
};
